package common

import (
)

func ENV_HOLISTIC_DATABASE_HOSTNAME() string {
	return "HOLISTIC_DATABASE_HOSTNAME"
}

func ENV_HOLISTIC_DATABASE_PORT_NUMBER() string {
	return "HOLISTIC_DATABASE_PORT_NUMBER"
}

func ENV_HOLISTIC_DATABASE_NAME() string {
	return "HOLISTIC_DATABASE_NAME"
}

func ENV_HOLISTIC_DATABASE_ROOT_USERNAME() string {
	return "HOLISTIC_DATABASE_ROOT_USERNAME"
}

func ENV_HOLISTIC_DATABASE_ROOT_PASSWORD() string {
	return "HOLISTIC_DATABASE_ROOT_PASSWORD"
}

func ENV_HOLISTIC_HOST_NUMBER_OF_USERS() string {
	return "HOLISTIC_HOST_NUMBER_OF_USERS"
}

func CONSTANT_HOLISTIC_DATABASE_MIGRATION_USERNAME() string {
	return "holistic_mig"
}

func CONSTANT_HOLISTIC_DATABASE_WRITE_USERNAME() string {
	return "holistic_w"
}

func CONSTANT_HOLISTIC_DATABASE_READ_USERNAME() string {
	return "holistic_r"
}



